### PR TITLE
update bibtex entry

### PR DESCRIPTION
**Pull request by ranocha**

### CODE REVIEW

**Comment by philipheinisch** [comment]
Add a  HOWPUBLISHED =line?

**Comment by ranocha** [comment]
> Add a HOWPUBLISHED =line?

What should we add in that line?
1. `howpublished={github}, url={https://github.com/MuMPlaCL/InductionEq}`
2. `howpublished={\url{https://github.com/MuMPlaCL/InductionEq}}`
3. Something else?

**Comment by philipheinisch** [comment]
It seems to me that howpublished={\url{https://github.com/MuMPlaCL/InductionEq}} is the most common format.

**Comment by ranocha** [comment]
Done. You can rebase & merge if you like. (And approve the PR before.)

**Pull request merged**
