### PR TITLE
use DOI pointing to the latest release

### PR DESCRIPTION
**Pull request by ranocha**
Since we have several releases, it might be best to use the DOI pointing to the latest release everywhere.

### CODE REVIEW

**Comment by philipheinisch** [comment]
Maybe add a .zenodo.json file to fix affiliations and names and license?
{
    "description": "A set of tools for numerically solving the nonlinear magnetic induction equation with Hall effect in OpenCL", 
    "license": "CC BY-NC-ND 4.0", 
    "title": "MuMPlaCL/InductionEq: Update License Version and Improve Naming of Coefficients", 
    "version": "v1.1.0", 
    "upload_type": "software", 
    "publication_date": "2018-10-02", 
    "creators": [
        {
            "affiliation": "TU Braunschweig", 
            "name": "Hendrik Ranocha"
        }, 
        {
			"affiliation": "TU Braunschweig", 
            "name": "Katharina Ostaszewski"
        }, 
        {
			"affiliation": "TU Braunschweig", 
            "name": "Philip Heinisch"
        }
    ], 
    "access_right": "open", 
    "related_identifiers": [
        {
            "scheme": "url", 
            "identifier": "https://github.com/MuMPlaCL/InductionEq/tree/v1.1.0", 
            "relation": "isSupplementTo"
        }, 
        {
            "scheme": "doi", 
            "identifier": "10.5281/zenodo.1434408", 
            "relation": "isVersionOf"
        }
    ]
}

**Comment by ranocha** [comment]
That sounds good. Could you add it, please?

**Comment by ranocha** [comment]
Maybe we can merge this PR and work on the zenodo part later? You could file an issue for that.

**Review by philipheinisch — APPROVED** [review]
DOI change looks good.

**Pull request merged**
